repos:
  - repo: local
    hooks:
      - id: mojo-format
        name: mojo-format
        entry: pixi run format
        language: system
        files: '\.(mojo|🔥|py)$'
        stages: [pre-commit]
      # - id: autodoc
      #   name: mautodoc
      #   entry: magic run doc_pages
      #   language: system
      #   files: '\.(mojo|🔥|py)$'
      #   stages: [pre-commit]
