repos:
  - repo: local
    hooks:
      - id: mojo-format
        name: mojo-format
        entry: magic run mojo format
        language: system
        files: '\.(mojo|🔥|py)$'
        stages: [pre-commit]