site_name: NuMojo
docs_dir: "./docs"
# nav:
    # - Home: index.md
    # - "Getting Started":
    #     Installation: getting_started/install.md
    # - Docs:
    #     - core:
    #         Constants: docs/core/constants.md
    #         Array Creation Routines: docs/core/array_creation_routines.md
    #         Ndarray Utils: docs/core/ndarray_utils.md
    #         Array Manipulation Routines: docs/core/array_manipulation_routines.md
    #         Datatypes: docs/core/datatypes.md
    #         Ndarray: docs/core/ndarray.md
    #         Sort: docs/core/sort.md
    #         Random: docs/core/random.md
    #         Utility Funcs: docs/core/utility_funcs.md
    #     - math:
    #         Check: docs/math/check.md
    #         Math Funcs: docs/math/math_funcs.md
    #         Interpolate: docs/math/interpolate.md
    #         Trig: docs/math/trig.md
    #         Comparison: docs/math/comparison.md
    #         Arithmetic: docs/math/arithmetic.md
    #         statistics:
    #             Stats: docs/math/statistics/stats.md
    #             Cumulative Reduce: docs/math/statistics/cumulative_reduce.md
    #         calculus:
    #             Integral: docs/math/calculus/integral.md
    #             Differentiation: docs/math/calculus/differentiation.md
    #         linalg:
    #             Linalg: docs/math/linalg/linalg.md
    #             Matmul: docs/math/linalg/matmul.md
    #     - traits:
    #         Backend: docs/traits/backend.md
    #         # Ndarraytraits: docs/traits/NDArrayTraits.mdd





theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
    #   permalink: true
      toc_depth: 4