name: Run pre-commit
on:
  # Run pre-commit on pull requests
  pull_request:
  # Add a workflow_dispatch event to run pre-commit manually
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install magic
        run: |
          curl -ssL https://magic.modular.com/deb181c4-455c-4abe-a263-afcff49ccf67 | bash
    
      - name: Add path
        run: |
          echo "MODULAR_HOME=$HOME/.modular" >> $GITHUB_ENV
          echo "$HOME/.modular/bin"  >> $GITHUB_PATH
          echo "$HOME/.modular/pkg/packages.modular.com_mojo/bin"  >> $GITHUB_PATH

      - name: Activate virtualenv
        run: |
          python3 -m venv $HOME/venv/
          . $HOME/venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      
      - name: Run pre-commit
        run: | 
          magic install
          pre-commit run --all-files