name: Run pre-commit
on:
  # Run pre-commit on pull requests
  pull_request:
  # Add a workflow_dispatch event to run pre-commit manually
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Magic
        run: |
          curl -ssL https://magic.modular.com/ff414efd-16ac-4bf3-8efc-50b059272ab6 | bash

          # Add magic to PATH
          echo "$HOME/.modular/bin" >> $GITHUB_PATH

          "$HOME/.modular/bin/magic" self-update
          
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      
      - name: Run pre-commit
        run: pre-commit run --all-files